version: '2'

services:
  nginx:
    # Dockerfileで設定している設定ファイルを格納したnginxを利用する（設定なしの場合：image: nginx:latest）
    build: ./nginx
    environment:
          TZ: Asia/Tokyo
    ports:
        - "8888:80"
    # マウントするディレクトリを指定(フロントの資材)
    volumes:
        - /Users/akira/IdeaProjects/studyCode/angular-tour-of-heroes/dist:/var/www/
        # - /Users/akira/IdeaProjects/studyCode/cookie/dist:/usr/share/nginx

