version: '2'

services:
  nginx:
    # Dockerfileで設定している設定ファイルを格納したnginxを利用する（設定なしの場合：image: nginx:latest）
    build: ./server/nginx
    environment:
          TZ: Asia/Tokyo
    ports:
        - "7777:80"
    # マウントするディレクトリを指定(フロントの資材)
    volumes:
        - ./dist:/var/www/
        # - ./dist:/usr/share/nginx
